<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Veyr.Check</AssemblyName>
    <RootNamespace>Veyr.Check</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\tools\Veyr.Check\**\*.cs" />
    <ProjectReference Include="..\Veyr.Sim\Veyr.Sim.csproj" />
    <ProjectReference Include="..\Veyr.Content\Veyr.Content.csproj" />
  </ItemGroup>
</Project>
