// Writes server/seed.sql from the game's shared data tables (src/game/data/*.ts, plus the trades
// in content.ts), so the server rolls the same loot, crafts the same recipes, knows the same
// foes, doors, stations, shops, bosses and quests as the client.
//   node --experimental-strip-types server/gen-seed.mjs
//
// Every position in the data is local to its zone; the server stores WORLD positions
// (the zone's origin ox + local x, z), so they are converted here.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { TRADES } from "../src/game/content.ts";
import { BOSSES } from "../src/game/data/bosses.ts";
import { ITEMS, RECIPES } from "../src/game/data/items.ts";
import { LEVEL_XP, MOB_XP } from "../src/game/data/progression.ts";
import { QUESTS } from "../src/game/data/quests.ts";
import { SELL_RATE, SHOPS } from "../src/game/data/shops.ts";
import { CACHE_DEFS, MOB_LOOT, MOB_SPAWNS, NODE_DEFS, WORLD_FLAGS } from "../src/game/data/world.ts";
import { PORTALS, SHRINES, STATIONS, ZONES } from "../src/game/data/zones.ts";

// ------------------------------------------------------------------ checks: a bad reference fails here, not in the database
const problems = [];
const item = (id, where) => {
  if (!ITEMS[id]) problems.push(`${where}: unknown item ${id}`);
};
const zone = (id, where) => {
  if (!ZONES[id]) problems.push(`${where}: unknown zone ${id}`);
};
for (const r of RECIPES) {
  item(r.out, r.id);
  for (const i of r.inputs) item(i.id, r.id);
}
for (const t of TRADES) {
  item(t.get.id, t.id);
  for (const g of t.give) item(g.id, t.id);
}
for (const [kind, list] of Object.entries(MOB_LOOT)) for (const [id] of list) item(id, "loot " + kind);
for (const [key, , , , z] of MOB_SPAWNS) zone(z, "spawn " + key);
for (const n of NODE_DEFS) item(n.item, n.id);
for (const c of CACHE_DEFS) {
  zone(c.zone, c.id);
  for (const [id] of c.items) item(id, c.id);
}
for (const p of PORTALS) {
  zone(p.from, p.id);
  zone(p.to, p.id);
}
for (const s of [...SHRINES, ...STATIONS]) zone(s.zone, s.id);
for (const s of SHOPS) {
  zone(s.zone, s.id);
  for (const [id] of s.stock) item(id, s.id);
}
for (const b of Object.values(BOSSES)) {
  zone(b.zone, b.id);
  for (const [id] of b.rewards) item(id, b.id);
}
const questIds = new Set(QUESTS.map((q) => q.id));
for (const q of QUESTS) {
  for (const r of q.requires) if (!questIds.has(r)) problems.push(`${q.id}: requires unknown quest ${r}`);
  for (const [id] of q.rewards.items) item(id, q.id);
  for (const s of q.steps) {
    if ((s.k === "have" || s.k === "give") && s.item) for (const id of s.item.split("|")) item(id, q.id);
    if (s.k === "reach") zone(s.zone, q.id);
    if (s.k === "boss" && !BOSSES[s.boss]) problems.push(`${q.id}: unknown boss ${s.boss}`);
  }
}
if (problems.length) {
  console.error("gen-seed: the data has broken references:\n  " + problems.join("\n  "));
  process.exit(1);
}

// ------------------------------------------------------------------ SQL
const json = (v) => ({ json: v });
const q = (v) =>
  v === null || v === undefined
    ? "null"
    : typeof v === "object" && "json" in v
      ? "'" + JSON.stringify(v.json).replace(/'/g, "''") + "'::jsonb"
      : typeof v === "string"
        ? "'" + v.replace(/'/g, "''") + "'"
        : String(v);
const rows = (list) => list.map((r) => "(" + r.map(q).join(", ") + ")").join(",\n  ");
const out = ["-- generated by server/gen-seed.mjs from src/game/data/*.ts and src/game/content.ts; do not edit", "begin;"];

// Upserts only, so the seed can be re-applied to a live project. A row removed from the data
// has to be removed from the database by hand.
const upsert = (table, cols, keys, list) => {
  if (!list.length) return;
  const rest = cols.filter((c) => !keys.includes(c));
  const set = rest.length ? "do update set " + rest.map((c) => `${c} = excluded.${c}`).join(", ") : "do nothing";
  out.push(`insert into ${table} (${cols.join(", ")}) values\n  ${rows(list)}\non conflict (${keys.join(", ")}) ${set};`);
};
/** world x of a zone-local x */
const wx = (z, x) => ZONES[z].ox + x;


// No loop may print crowns: buying an item and selling it back, or buying a recipe's inputs,
// crafting and selling the result, must always lose money.
{
  const sell = (id) => (ITEMS[id] && !ITEMS[id].soulbound ? Math.floor(ITEMS[id].value * SELL_RATE) : 0);
  const buy = {};
  for (const s of SHOPS) for (const [id, price] of s.stock) buy[id] = Math.min(buy[id] ?? Infinity, price ?? ITEMS[id].value);
  const bad = [];
  for (const [id, cost] of Object.entries(buy)) if (sell(id) >= cost) bad.push(`${id}: buy ${cost}, sell ${sell(id)}`);
  for (const r of RECIPES) {
    if (!r.inputs.every((i) => buy[i.id] !== undefined)) continue;
    const cost = r.inputs.reduce((a, i) => a + buy[i.id] * i.n, 0);
    const gain = sell(r.out) * (r.n ?? 1);
    if (gain >= cost) bad.push(`${r.id}: inputs ${cost}, sells for ${gain}`);
  }
  if (bad.length) {
    console.error("crowns from nothing:\n  " + bad.join("\n  "));
    process.exit(1);
  }
}

upsert("vm_item_defs", ["id", "name", "kind", "stack", "damage", "tier", "slot", "moveset", "heal", "soulbound", "defence", "rarity", "value", "family"], ["id"],
  Object.values(ITEMS).map((d) => [d.id, d.name, d.kind, d.stack, d.damage, d.tier, d.slot, d.moveset, d.heal, d.soulbound, d.defence, d.rarity, d.value, d.family]));
upsert("vm_recipes", ["id", "out_item", "station", "n"], ["id"], RECIPES.map((r) => [r.id, r.out, r.station, r.n ?? 1]));
upsert("vm_recipe_inputs", ["recipe", "item", "n"], ["recipe", "item"], RECIPES.flatMap((r) => r.inputs.map((i) => [r.id, i.id, i.n])));
upsert("vm_trades", ["id", "get_item", "get_n"], ["id"], TRADES.map((t) => [t.id, t.get.id, t.get.n]));
upsert("vm_trade_inputs", ["trade", "item", "n"], ["trade", "item"], TRADES.flatMap((t) => t.give.map((g) => [t.id, g.id, g.n])));
const loot = Object.entries(MOB_LOOT).flatMap(([kind, list]) => list.map(([id, n, chance]) => [kind, id, n, chance]));
upsert("vm_loot", ["kind", "item", "n", "chance"], ["kind", "item"], loot);
upsert("vm_mob_kinds", ["kind", "xp"], ["kind"], Object.entries(MOB_XP).map(([kind, xp]) => [kind, xp]));
// indoor zones, soldiers and the kennelmaster do not come back
const spawns = MOB_SPAWNS.map(([key, kind, x, z, zn]) => [key, kind, zn === "castle", !ZONES[zn].indoor && kind !== "soldier" && kind !== "kennelmaster", zn, wx(zn, x), z]);
upsert("vm_mob_spawns", ["key", "kind", "dungeon", "respawns", "zone", "x", "z"], ["key"], spawns);
upsert("vm_nodes", ["id", "item", "tier", "seal", "max_left", "zone", "x", "z"], ["id"],
  NODE_DEFS.map((n) => [n.id, n.item, n.tier, n.seal, n.max, n.zone, n.x === undefined ? null : wx(n.zone, n.x), n.z ?? null]));
upsert("vm_caches", ["cache", "item", "n"], ["cache", "item"], CACHE_DEFS.flatMap((c) => c.items.map(([id, n]) => [c.id, id, n])));
upsert("vm_cache_spots", ["cache", "zone", "x", "z"], ["cache"], CACHE_DEFS.map((c) => [c.id, c.zone, wx(c.zone, c.x), c.z]));

upsert("vm_zones", ["id", "ox", "indoor", "min_x", "max_x", "min_z", "max_z"], ["id"],
  Object.values(ZONES).map((z) => [z.id, z.ox, z.indoor, z.bounds.minX, z.bounds.maxX, z.bounds.minZ, z.bounds.maxZ]));
upsert("vm_stations", ["id", "kind", "zone", "x", "z", "r"], ["id"], STATIONS.map((s) => [s.id, s.kind, s.zone, wx(s.zone, s.x), s.z, s.r]));
upsert("vm_portals", ["id", "from_zone", "x", "z", "r", "to_zone", "tx", "tz", "flag"], ["id"],
  PORTALS.map((p) => [p.id, p.from, wx(p.from, p.x), p.z, p.r, p.to, wx(p.to, p.tx), p.tz, p.flag ?? null]));
upsert("vm_shrines", ["id", "zone", "x", "z"], ["id"], SHRINES.map((s) => [s.id, s.zone, wx(s.zone, s.x), s.z]));

upsert("vm_bosses", ["id", "name", "zone", "x", "z", "r", "reach", "hp", "scale", "xp", "crowns", "rewards", "flag"], ["id"],
  Object.values(BOSSES).map((b) => [b.id, b.name, b.zone, wx(b.zone, b.x), b.z, b.r, b.reach, b.hp, b.scale, b.xp, b.crowns, json(b.rewards), b.flag]));
upsert("vm_shops", ["id", "zone", "x", "z", "keeper", "buys"], ["id"], SHOPS.map((s) => [s.id, s.zone, wx(s.zone, s.x), s.z, s.keeper, s.buys]));
upsert("vm_shop_stock", ["shop", "item", "price"], ["shop", "item"],
  SHOPS.flatMap((s) => s.stock.map(([id, price]) => [s.id, id, price ?? ITEMS[id].value])));
upsert("vm_quests", ["id", "def"], ["id"], QUESTS.map((qd) => [qd.id, json(qd)]));
upsert("vm_world_flag_rules", ["flag", "needs_mob", "needs_flag"], ["flag"], WORLD_FLAGS.map((f) => [f.flag, f.needsMob ?? null, f.needsFlag ?? null]));

// cookie_hp is kept for anything that still reads it; vm_bosses is the truth
upsert("vm_config", ["key", "value"], ["key"], [
  ["cookie_hp", json(BOSSES.cookie.hp)],
  ["level_xp", json(LEVEL_XP)],
  ["sell_rate", json(SELL_RATE)],
]);
out.push("commit;", "");

const file = join(dirname(fileURLToPath(import.meta.url)), "seed.sql");
writeFileSync(file, out.join("\n\n"));
console.log("wrote", file);
