// Writes server/seed.sql from the game's content tables, so the server rolls the same loot,
// crafts the same recipes, and knows the same foes as the client.
//   node --experimental-strip-types server/gen-seed.mjs
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { CACHES, COOKIE_HP, ITEMS, MOB_LOOT, MOB_SPAWNS, NODE_DEFS, RECIPES, TRADES } from "../src/game/content.ts";

const q = (v) => (v === null || v === undefined ? "null" : typeof v === "string" ? "'" + v.replace(/'/g, "''") + "'" : String(v));
const rows = (list) => list.map((r) => "(" + r.map(q).join(", ") + ")").join(",\n  ");
const out = ["-- generated by server/gen-seed.mjs from src/game/content.ts; do not edit", "begin;"];

const items = Object.values(ITEMS).map((d) => [d.id, d.name, d.kind, d.stack, d.damage, d.tier, d.slot, d.moveset, d.heal, d.soulbound]);
out.push(`insert into vm_item_defs (id, name, kind, stack, damage, tier, slot, moveset, heal, soulbound) values
  ${rows(items)}
on conflict (id) do update set name = excluded.name, kind = excluded.kind, stack = excluded.stack, damage = excluded.damage,
  tier = excluded.tier, slot = excluded.slot, moveset = excluded.moveset, heal = excluded.heal, soulbound = excluded.soulbound;`);

// Upserts only, so the seed can be re-applied to a live project. A row removed from content.ts
// has to be removed from the database by hand.
const upsert = (table, cols, keys, list) => {
  const rest = cols.filter((c) => !keys.includes(c));
  const set = rest.length ? "do update set " + rest.map((c) => `${c} = excluded.${c}`).join(", ") : "do nothing";
  out.push(`insert into ${table} (${cols.join(", ")}) values\n  ${rows(list)}\non conflict (${keys.join(", ")}) ${set};`);
};
upsert("vm_recipes", ["id", "out_item", "station"], ["id"], RECIPES.map((r) => [r.id, r.out, r.station]));
upsert("vm_recipe_inputs", ["recipe", "item", "n"], ["recipe", "item"], RECIPES.flatMap((r) => r.inputs.map((i) => [r.id, i.id, i.n])));
upsert("vm_trades", ["id", "get_item", "get_n"], ["id"], TRADES.map((t) => [t.id, t.get.id, t.get.n]));
upsert("vm_trade_inputs", ["trade", "item", "n"], ["trade", "item"], TRADES.flatMap((t) => t.give.map((g) => [t.id, g.id, g.n])));
const loot = Object.entries(MOB_LOOT).flatMap(([kind, list]) => list.map(([item, n, chance]) => [kind, item, n, chance]));
upsert("vm_loot", ["kind", "item", "n", "chance"], ["kind", "item"], loot);
const spawns = MOB_SPAWNS.map(([key, kind, , , dungeon]) => [key, kind, dungeon, !dungeon && kind !== "soldier"]);
upsert("vm_mob_spawns", ["key", "kind", "dungeon", "respawns"], ["key"], spawns);
upsert("vm_nodes", ["id", "item", "tier", "seal", "max_left"], ["id"], NODE_DEFS.map((n) => [n.id, n.item, n.tier, n.seal, n.max]));
const caches = Object.entries(CACHES).flatMap(([cache, list]) => list.map(([item, n]) => [cache, item, n]));
upsert("vm_caches", ["cache", "item", "n"], ["cache", "item"], caches);

out.push(`insert into vm_config (key, value) values ('cookie_hp', '${COOKIE_HP}'::jsonb)
on conflict (key) do update set value = excluded.value;`);
out.push("commit;", "");

const file = join(dirname(fileURLToPath(import.meta.url)), "seed.sql");
writeFileSync(file, out.join("\n\n"));
console.log("wrote", file);
