-- generated by server/gen-seed.mjs from src/game/content.ts; do not edit

begin;

insert into vm_item_defs (id, name, kind, stack, damage, tier, slot, moveset, heal, soulbound) values
  ('wpn_fists', 'Fists', 'weapon', 1, 4, 0, 'main', 'fists', 0, false),
  ('mat_wood', 'Wood', 'mat', 99, 0, 0, 'none', '', 0, false),
  ('mat_flint', 'Flint', 'mat', 99, 0, 0, 'none', '', 0, false),
  ('mat_fibre', 'Fibre', 'mat', 99, 0, 0, 'none', '', 0, false),
  ('mat_stone', 'Stone', 'mat', 99, 0, 0, 'none', '', 0, false),
  ('mat_bone', 'Bone', 'mat', 99, 0, 0, 'none', '', 0, false),
  ('mat_leather', 'Leather', 'mat', 99, 0, 0, 'none', '', 0, false),
  ('mat_copper', 'Copper', 'mat', 99, 0, 0, 'none', '', 0, false),
  ('mat_iron', 'Iron', 'mat', 99, 0, 0, 'none', '', 0, false),
  ('wpn_stone_knife', 'Stone Knife', 'weapon', 1, 10, 1, 'main', 'knife', 0, false),
  ('wpn_stone_pick', 'Stone Pick', 'weapon', 1, 7, 2, 'main', 'pick', 0, false),
  ('wpn_copper_pick', 'Copper Pick', 'weapon', 1, 9, 3, 'main', 'pick', 0, false),
  ('wpn_copper_sword', 'Copper Sword', 'weapon', 1, 14, 3, 'main', 'sword', 0, false),
  ('wpn_iron_sword', 'Iron Sword', 'weapon', 1, 19, 4, 'main', 'sword', 0, false),
  ('wpn_cookie_blade', 'Cookie''s Blade', 'weapon', 1, 22, 4, 'main', 'cookie_blade', 0, true),
  ('wpn_cookie_pick', 'Cookie''s Pickaxe', 'weapon', 1, 16, 4, 'main', 'cookie_pick', 0, true),
  ('key_cookie_core', 'Cookie''s Core', 'key', 1, 0, 4, 'none', '', 0, true),
  ('wpn_smacko', 'Smacko', 'weapon', 1, 18, 4, 'main', 'smacko', 0, true),
  ('arm_stump_shield', 'Stump Shield', 'armour', 1, 0, 0, 'off', 'shield', 0, false),
  ('arm_cloth', 'Cloth', 'armour', 1, 0, 0, 'none', '', 0, false),
  ('cons_bandage', 'Bandage', 'consumable', 10, 0, 0, 'none', '', 28, false)
on conflict (id) do update set name = excluded.name, kind = excluded.kind, stack = excluded.stack, damage = excluded.damage,
  tier = excluded.tier, slot = excluded.slot, moveset = excluded.moveset, heal = excluded.heal, soulbound = excluded.soulbound;

insert into vm_recipes (id, out_item, station) values
  ('recipe_stone_knife', 'wpn_stone_knife', 'hand'),
  ('recipe_bandage', 'cons_bandage', 'hand'),
  ('recipe_stump_shield', 'arm_stump_shield', 'bench'),
  ('recipe_stone_pick', 'wpn_stone_pick', 'bench'),
  ('recipe_copper_sword', 'wpn_copper_sword', 'forge'),
  ('recipe_copper_pick', 'wpn_copper_pick', 'forge'),
  ('recipe_iron_sword', 'wpn_iron_sword', 'forge')
on conflict (id) do update set out_item = excluded.out_item, station = excluded.station;

insert into vm_recipe_inputs (recipe, item, n) values
  ('recipe_stone_knife', 'mat_flint', 2),
  ('recipe_stone_knife', 'mat_wood', 1),
  ('recipe_bandage', 'mat_fibre', 2),
  ('recipe_stump_shield', 'mat_wood', 3),
  ('recipe_stump_shield', 'mat_fibre', 1),
  ('recipe_stone_pick', 'mat_flint', 3),
  ('recipe_stone_pick', 'mat_wood', 2),
  ('recipe_stone_pick', 'mat_fibre', 1),
  ('recipe_copper_sword', 'mat_copper', 5),
  ('recipe_copper_sword', 'mat_wood', 1),
  ('recipe_copper_sword', 'mat_flint', 1),
  ('recipe_copper_pick', 'mat_copper', 4),
  ('recipe_copper_pick', 'mat_wood', 2),
  ('recipe_copper_pick', 'wpn_stone_pick', 1),
  ('recipe_iron_sword', 'mat_iron', 3),
  ('recipe_iron_sword', 'mat_leather', 1),
  ('recipe_iron_sword', 'mat_wood', 1)
on conflict (recipe, item) do update set n = excluded.n;

insert into vm_trades (id, get_item, get_n) values
  ('t_bandage', 'cons_bandage', 1),
  ('t_copper', 'mat_copper', 2),
  ('t_flint', 'mat_flint', 2),
  ('t_fibre', 'mat_fibre', 3)
on conflict (id) do update set get_item = excluded.get_item, get_n = excluded.get_n;

insert into vm_trade_inputs (trade, item, n) values
  ('t_bandage', 'mat_bone', 2),
  ('t_copper', 'mat_leather', 2),
  ('t_flint', 'mat_wood', 3),
  ('t_fibre', 'mat_stone', 2)
on conflict (trade, item) do update set n = excluded.n;

insert into vm_loot (kind, item, n, chance) values
  ('wolf', 'mat_bone', 1, 1),
  ('wolf', 'mat_leather', 1, 0.35),
  ('goblin', 'mat_leather', 1, 0.8),
  ('goblin', 'mat_fibre', 2, 0.5),
  ('redcap', 'mat_copper', 3, 1),
  ('redcap', 'cons_bandage', 1, 1),
  ('redcap', 'mat_leather', 2, 1),
  ('soldier', 'cons_bandage', 1, 0.25),
  ('horse', 'cons_bandage', 2, 1),
  ('deer', 'mat_leather', 2, 1),
  ('deer', 'mat_bone', 1, 0.5)
on conflict (kind, item) do update set n = excluded.n, chance = excluded.chance;

insert into vm_mob_spawns (key, kind, dungeon, respawns) values
  ('w1', 'wolf', false, true),
  ('w2', 'wolf', false, true),
  ('w3', 'wolf', false, true),
  ('w4', 'wolf', false, true),
  ('w5', 'wolf', false, true),
  ('w6', 'wolf', false, true),
  ('w7', 'wolf', false, true),
  ('g1', 'goblin', false, true),
  ('g2', 'goblin', false, true),
  ('g3', 'goblin', false, true),
  ('g4', 'redcap', false, true),
  ('d1', 'deer', false, true),
  ('d2', 'deer', false, true),
  ('d3', 'deer', false, true),
  ('d4', 'deer', false, true),
  ('d5', 'deer', false, true),
  ('s1', 'soldier', false, false),
  ('s2', 'soldier', false, false),
  ('dm1', 'mouse', true, false),
  ('dm2', 'mouse', true, false),
  ('ds1', 'soldier', true, false),
  ('ds2', 'soldier', true, false),
  ('dm3', 'mouse', true, false),
  ('ds3', 'soldier', true, false),
  ('ds4', 'soldier', true, false),
  ('dh', 'horse', true, false)
on conflict (key) do update set kind = excluded.kind, dungeon = excluded.dungeon, respawns = excluded.respawns;

insert into vm_nodes (id, item, tier, seal, max_left) values
  ('flint_0', 'mat_flint', 0, null, 3),
  ('flint_1', 'mat_flint', 0, null, 3),
  ('flint_2', 'mat_flint', 0, null, 3),
  ('flint_3', 'mat_flint', 0, null, 3),
  ('wood_0', 'mat_wood', 0, null, 3),
  ('wood_1', 'mat_wood', 0, null, 3),
  ('wood_2', 'mat_wood', 0, null, 3),
  ('wood_3', 'mat_wood', 0, null, 3),
  ('wood_4', 'mat_wood', 0, null, 3),
  ('fibre_0', 'mat_fibre', 0, null, 3),
  ('fibre_1', 'mat_fibre', 0, null, 3),
  ('fibre_2', 'mat_fibre', 0, null, 3),
  ('fibre_3', 'mat_fibre', 0, null, 3),
  ('fibre_4', 'mat_fibre', 0, null, 3),
  ('fibre_5', 'mat_fibre', 0, null, 3),
  ('stone_0', 'mat_stone', 0, null, 3),
  ('stone_1', 'mat_stone', 0, null, 3),
  ('stone_2', 'mat_stone', 0, null, 3),
  ('copper_0', 'mat_copper', 2, null, 3),
  ('copper_1', 'mat_copper', 2, null, 3),
  ('copper_2', 'mat_copper', 2, null, 3),
  ('copper_3', 'mat_copper', 2, null, 3),
  ('iron_0', 'mat_iron', 4, 'seal_cookie', 4),
  ('iron_1', 'mat_iron', 4, 'seal_cookie', 4)
on conflict (id) do update set item = excluded.item, tier = excluded.tier, seal = excluded.seal, max_left = excluded.max_left;

insert into vm_caches (cache, item, n) values
  ('chest', 'cons_bandage', 2),
  ('chest', 'mat_fibre', 2),
  ('chest', 'mat_wood', 1),
  ('hollow', 'mat_copper', 3),
  ('hollow', 'mat_leather', 1),
  ('hollow', 'cons_bandage', 1)
on conflict (cache, item) do update set n = excluded.n;

insert into vm_config (key, value) values ('cookie_hp', '280'::jsonb)
on conflict (key) do update set value = excluded.value;

commit;

