<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Veyr.Client.Core</AssemblyName>
    <RootNamespace>Veyr.Client.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Packages\com.veyrmarch.clientcore\Runtime\**\*.cs" />
    <ProjectReference Include="..\Veyr.Sim\Veyr.Sim.csproj" />
    <ProjectReference Include="..\Veyr.Content\Veyr.Content.csproj" />
    <ProjectReference Include="..\Veyr.Net\Veyr.Net.csproj" />
  </ItemGroup>
</Project>
